[package]
name = "problem_one_cargo"
version = "0.1.0"
authors = ["EndyZone <enzo.arenas1997@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
